name: sos_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.3.0
  image_picker: ^0.8.6+1
  firebase_messaging: ^14.4.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.27.0
  flutter_local_notifications: ^17.0.0
  flutter_dotenv: ^5.0.2
  share_plus: ^7.1.0
  go_router: ^10.1.0
  google_sign_in: ^6.1.5
  gap: ^3.0.1
  dio: ^5.4.0
  flutter_svg: ^2.0.9
  gallery_saver: ^2.3.2
  device_info: ^2.0.0
  flutter_image_compress: ^2.1.0
  sqflite: ^2.3.2
  pinput: ^4.0.0
  another_flushbar: ^1.12.30
  flutter_staggered_grid_view: ^0.7.0
  flutter_app_badger: ^1.5.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Kh_Bl_LazySmooth_Regular
      fonts:
        - asset: assets/font/Kh_Bl_LazySmooth_Regular.ttf
  assets:
    - .env
    - assets/image/
    - assets/icons/
