name: sos_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.3.0
  image_picker: ^0.8.6+1
  firebase_messaging: ^14.4.0
  firebase_auth: ^4.9.0
  flutter_local_notifications: ^13.0.0
  flutter_dotenv: ^5.0.2
  share_plus: ^7.1.0
  go_router: ^10.1.0
  google_sign_in: ^6.1.5
  gap: ^3.0.1
  dio: ^5.4.0
  top_snackbar_flutter: ^3.1.0
  lite_rolling_switch: ^1.0.1
  flutter_svg: ^2.0.9
  gallery_saver: ^2.3.2
  device_info: ^2.0.0
  http_parser: ^4.0.0
  flutter_image_compress: ^2.1.0










dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: preahvihear
      fonts:
        - asset: assets/font/Moulpali.ttf
        - asset: assets/font/Siemreap.ttf
  assets:
    - .env
    - assets/image/