name: sos_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.3.0
  image_picker: ^0.8.6+1
  firebase_messaging: ^14.4.0
  firebase_auth: ^4.9.0
  flutter_local_notifications: ^13.0.0
  flutter_dotenv: ^5.0.2
  animated_text_kit: ^4.2.2
  share_plus: ^7.1.0
  go_router: ^10.1.0
  google_sign_in: ^6.1.5
  gap: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: preahvihear
      fonts:
        - asset: assets/font/preahvihear.ttf
  assets:
    - .env
    - assets/image/