name: sos_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0 
  get: ^4.6.5
  get_it: ^7.2.0
  injectable: ^1.5.3
  http: ^0.13.5
  global_configuration: ^2.0.0-nullsafety.1
  shared_preferences: ^2.0.15
  go_router: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.17
  flutter_statusbarcolor_ns: ^0.5.0

# dev_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.1
  freezed: ^2.2.0
  build_runner: ^2.3.0
  injectable_generator: ^1.5.4
flutter_native_splash:
  color: '#000000'
  #image: 'assets/image/general/White.png'
  android: true
  ios: true

flutter:
  uses-material-design: true
  fonts:
    - family: hanuman
      fonts:
        - asset: assets/font/hanuman.ttf
  assets:
    - assets/cfg/