name: sos_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.1
  freezed: ^2.2.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
  fonts:
    - family: siemreap
      fonts:
        - asset: assets/font/Siemreap.ttf
